# Copyright (c) 2019, UK HealthCare (https://ukhealthcare.uky.edu) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##########################


apiVersion: v1
kind: Secret
metadata:
  name: camunda-bpm-platform-apikey-secret
type: Opaque
data:
  apikey: YWRtaW4=

---

apiVersion: v1
kind: Service
metadata:
  name: camunda-bpm-platform
  labels:
    app: camunda-bpm-platform
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: camunda-bpm-platform
  type: LoadBalancer
  
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: camunda-bpm-platform
  labels:
    app: camunda-bpm-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-bpm-platform
  template:
    metadata:
      labels:
        app: camunda-bpm-platform
    spec:
      containers:
      - name: camunda-bpm-platform
        image: camunda/camunda-bpm-platform:tomcat-7.10.0
        ports:
        - containerPort: 8080
        env:
        - name: ApiKey
          valueFrom:
            secretKeyRef:
              name: camunda-bpm-platform-apikey-secret
              key: apikey
        #- name: DB_DRIVER
        #  value: 'com.mysql.jdbc.Driver'
        #- name: DB_URL
        #  value: 'jdbc:mysql://mariadb:3306/camunda'
        #- name: DB_USERNAME
        #  value: root
        #- name: DB_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: mariadb-root-secret
        #      key: password
        #- name: WAIT_FOR
        #  value: mariadb:3306
        #- name: WAIT_FOR_TIMEOUT
        #  value: '60'
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 3 
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          